### ISSUE TITLE
Unknow url type

### ISSUE THREAD

**Issue by superprzemo** [ZuinigeRijder/SolisCloud2PVOutput#25]
In log I have ERROR:
20230607 09:52:59: ERROR: https://www.soliscloud.com:13333/v1/api/userStationList -> unknown url type: https

solidcould_to_pvoutput.cfg  file filled according to README, of course with my API data to solis.

I have Raspberry PI 4B with Domoticz and Python 3.11.2 with R1.12.0  and I can not get data from solis_cloud. 
Please send me what I am doing wrong.

This is my config file:

[api_secrets]
send_to_pvoutput = False
soliscloud_api_id = myAPIkey
soliscloud_api_secret = mysecretAPI
soliscloud_api_url = https://www.soliscloud.com:13333
soliscloud_inverter_index = 0
pvoutput_api_key = 0
pvoutput_system_id = 0

[Domoticz]
send_to_domoticz = True
domot_url = http://192.168.8.166:8082
domot_power_generated_id = 374
domot_ac_volt_id = 379
domot_inverter_temp_id = 376
domot_volt_id = 36

**Comment by ZuinigeRijder** [comment]
It looks like python is missing some ssl libraries. So there is something with the python installation or search paths for python. 

Did you have multiple python versions installed?
Did you upgrade python?

Maybe you could make a small program doing a **https** request, to see if it is related to your environment/python and not related to SolisCloud2PVOutput?
E.g. using [this example](https://realpython.com/urllib-request/)

````
from urllib.request import urlopen
with urlopen("https://www.example.com") as response:
    body = response.read()

body[:15]
````

See also [here, where there is a possible cause for the problem](https://www.linode.com/community/questions/21480/urlopen-error-unknown-url-type-https).

**Comment by superprzemo** [comment]
Yes, you have right. I was install python with ssl and now SolisCloud2PVOutput works fine.
Thank you for support and great work :)
