### ISSUE TITLE
Python script error

### ISSUE THREAD

**Issue by telemarker73** [ZuinigeRijder/SolisCloud2PVOutput#27]
Hi after issues with cron on my NAS , I copied the scripts to my raspberry pi

Which version of python 3 should I use?
I get this error running python 3.9
Previous Python 3.4 had other issues, so upgraded to 3.9.15

![9152E292-1BEC-4715-8AB5-9E79D71AC972](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/assets/137273211/5f7c840c-666b-41c9-866d-d0fb07207270)

**Comment by telemarker73** [comment]
Thanks - yes missing ssl support, thanks for link I will attempt to resolve it

**Comment by telemarker73** [comment]
SSL added, now need to look into this certificate issue
![D606135D-B7FF-46F1-9D90-09FE23A61D33](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/assets/137273211/bb083ab6-e54e-42e3-a99e-8d2659eba798)

**Comment by telemarker73** [comment]
Update, found a certifi script to update certificates and it seems to be working now and uploading data to PVOutput
Get bad gateway 502 error occasionally

**Comment by ZuinigeRijder** [comment]
Good to see that you managed to get it working. The error "502: Bad Gateway" I also get regularly, that is because SolisCloud is often overloaded. But the script just tries again after a minute, nothing to worry about.

**Comment by telemarker73** [comment]
Thank you for the guidance and the work to create the scripts , appreciated

**Comment by ZuinigeRijder** [comment]
Closed.
