### ISSUE TITLE
generation remains at 20 Watts

### ISSUE THREAD

**Issue by 67Andre** [ZuinigeRijder/SolisCloud2PVOutput#28]
Hi,
From sunset, the generated amount remains at 20 Watts while the inverter produces 0 Watts. This value is written to PV output after which it is read into Domoticz and provides an incorrect summation of 20 Watts per 5 minutes until 11:59 PM.

`20231030 17:22:16: INFO: data=20231030,17:22,3510,20,,226.3,24.8,161.9
20231030 17:27:18: INFO: data=20231030,17:27,3511,20,,225.0,24.7,124.3
20231030 17:32:20: INFO: data=20231030,17:32,3512,20,,227.8,24.6,109.8
20231030 17:37:23: INFO: data=20231030,17:37,3513,20,,227.1,24.5,91.1
20231030 17:42:25: INFO: data=20231030,17:42,3514,20,,227.1,24.5,0 
20231030 23:00:23: INFO: Outside solar generation hours (5..23)
Exiting program to start fresh tomorrow
`

20231030 17:42:25: INFO: data=20231030,17:42,3514,**20**,,227.1,24.5,0 
This is the last value and doesn't go to 0 Watt

Thank you in advance

**Comment by ZuinigeRijder** [comment]
@67Andre 
I use the pac (Real-Time power) of SolisCloud for the energy generation. If I compare the SolisCloud data with the PVOutput data for my system, I see that SolisCloud is reporting 0.02 kW for Total Power, which I use in the calculations. So it seems consistent with the SolisCloud data. Apparently, as long as the SolisCloud inverter is not in deep sleep, it will report 0.02 kW. And will stop sending data to PVOutput and Domoticz when it is in deep sleep, so it will not send the 0 Watt to both.

Can you check if this is the same for you?
And is there maybe a problem in Domoticz, which expects 0 Watt to be send?

**Comment by 67Andre** [comment]
Today the energy generation started at 8:20 am and stopped at 5:40 pm. The total energy generation for today is 1,414kWh (Soliscloud). The same total power is also visible in PVoutput.org, the last line in the overview (5:40 PM) shows a value of 20Watt. 

> <html>
<body>


Date | Time | Energy | Efficiency | Power | Average | Normalised | Temperature | Voltage | Energy Used | Power Used
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01/11/23 | 17:40 | 1.414kWh | 0.604kWh/kW | 20W | 12W | 0.005kW/kW | 24.9C | 0.0V | 2.150kWh | 224W


</body>
</html>

Domoticz reads the last value ​​of PVoutput and continuously reads the 20 Watt value, resulting in an extra generated fictitious power of 20 Wh. Currently Domoticz displays a value of 1,641 kWh.

> 
![image](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/assets/149441911/99728301-57d8-473a-b225-d1a4d1c41783)

**Comment by ZuinigeRijder** [comment]
@67Andre Ok, so as I understands correctly, this is a problem in Domoticz software itself, it should check the timestamp and only update when there are new values. I do not have experience with Domoticz, so probably you have to submit an issue to the appropriate channels at Domoticz.

**Comment by ZuinigeRijder** [comment]
@67Andre Are you using [the option to also send the information to Domoticz](https://github.com/ZuinigeRijder/SolisCloud2PVOutput#domoticz)? See also [here](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/discussions/18). Would this solve your issue?

**Comment by 67Andre** [comment]
@ZuinigeRijder According to your advice, I wrote the values ​​directly to domoticz with a successful result, the energy generated is now equal to that of Soliscloud. Thank you very much for this solution.
